### PR TITLE
cleanup(unittest): Remove deprecated `garden-test` test framework

### LINKED ISSUE #1166: Cleanup deprecated unit tests (`bin/garden-test`)
**What would you like to be added**:
Old and deprecated code of `garden-test` should be removed in favor of the new PyTest based unit tests (rel. #720). To not confuse people, the deprecated code should be removed and the docs adjusted.

**Why is this needed**:
All legacy tests have been migrated to PyTest based `chroot`, `kvm` or other platform tests. With finishing of #720, #860, #730, #709 we may now finally remove this.

### PR DESCRIPTION
**Pull request by gyptazy**
cleanup(unittest): Remove deprecated `garden-test` test framework

**How to categorize this PR?**

/kind cleanup
/area os
/os garden-linux

**What this PR does / why we need it**:
 * Remove deprecated `garden-test` test framework (all tests are migrated to PyTest)
 * Adjust doc(s)

**Which issue(s) this PR fixes**:
Fixes #1166

**Release note**:

```feature user
NONE
```

### CODE REVIEW

**Review by chrinorse — CHANGES_REQUESTED** [review]
In build.sh in line 25 and 39 the unittests are still referenced

**Comment by gyptazy** [comment]
> In build.sh in line 25 and 39 the unittests are still referenced

@chrinorse, thanks for the hint. Fixed.

**Review by chrinorse — APPROVED** [review]
lgtm

**Review by Vincinator — APPROVED** [review]
lgtm

**Pull request merged**
