### PR TITLE
Enable Azure accelerated networking

### LINKED ISSUE #1198: Ensure that accelerated networking works on Azure
**What would you like to be added**:

First, accelerated networking should work on Azure out of the box as Garden Linux contains all the ingredients which are the mlx4 and mlx5 drivers as well as a cloud-init version >=19.4. 

There are two caveats, first we haven't tested it and second we disable network configuration in cloud-init which might prevent this particular configuration from being applied.

See Azure documentation: https://docs.microsoft.com/en-us/azure/virtual-network/accelerated-networking-overview#custom-images

**Why is this needed**:

### PR DESCRIPTION
**Pull request by marwinski**
**How to categorize this PR?**

/kind enhancement
/area os
/os garden-linux

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #1198

**Special notes for your reviewer**:

The Azure feature is described here: https://docs.microsoft.com/en-us/azure/virtual-network/accelerated-networking-overview

I have checked the configuration on the VM to ensure it is enabled and working. I will add an integration test for this later on.

**Release note**:

```feature user
Garden Linux supports Azure accelerated networking.
```

### CODE REVIEW

**Review by MrBatschner — APPROVED** [review]
/lgtm

**Comment by marwinski** [comment]
> ... but you might want to drop commit [5e957ba](https://github.com/gardenlinux/gardenlinux/commit/5e957ba02391df14159a0ef969a06f81646f7f76) from this PR as it would merge the changes you posted for review in PR #1216

done

**Comment by MrBatschner** [comment]
Can you please rebase this PR to latest `main` so that the checks can succeed?

/needs rebase

**Comment by marwinski** [comment]
done rebase

**Pull request merged**
