### PR TITLE
github: add labeler action 

### PR DESCRIPTION
**Pull request by Vincinator**
**What this PR does / why we need it**:

* Add github labeler action
    * must be merged to main before the new labeler action can assign labels to PRs 
    * test repo: https://github.com/Vincinator/test-labeler/pull/1 
* use PR template from gardenlinux/.github org repo

### CODE REVIEW

**Comment by Vincinator** [comment]
Requirement: Need label automation

**Comment by Vincinator** [comment]
Requirement: Conventional Commit Checker (other PR?)
Requirement: Static Code Checker (other PR?)

**Comment by Vincinator** [comment]
**Gardener Robot:** you write labels in the PR instead of using GitHub's UI. 
Pro:
- you don't need to use the GitHub UI  
Con:
- you need to know the naming of the Labels

**Labeler GH Action:** Automatically assign labels based on code path
Pro:
- don't need to do anything
Con:
- Things like `breaking-change` must still be assigned manually

**Comment by fwilhe** [comment]
Screenshot 2023-12-04 at 13 13 07

This sounds like it would affect us, but I don't see that config being set.

**Comment by Vincinator** [comment]
Set `dot: true` for labeler workflow

**Comment by fwilhe** [comment]
> Thanks! Added platform labels.
> 
> The `dot: true` setting is a good idea, don't see a reason why not to enable it. You?

No I don't see a reason against, but it does not seem to make a difference for our config as far as I understood now.

**Comment by Vincinator** [comment]
Change PR template here: 
https://github.com/gardenlinux/.github/blob/main/.github/pull_request_template.md

**Comment by Vincinator** [comment]
https://github.blog/changelog/2023-01-10-github-actions-support-for-organization-wide-required-workflows-public-beta/

This should be a required org-wide workflow

**Pull request merged**
