### PR TITLE
Add upload OCI workflow

### PR DESCRIPTION
**Pull request by mxmxchere**
Stuff left to do:

- [x] Switch downloading mechanism from S3 to GitHub Artifacts
- [x] include the new version of `glcli oci push...` with external signing
- [x] Include cosign tool to sign the artifacts

### CODE REVIEW

**Comment by mxmxchere** [comment]
The push OCI artifacts python-script should output a list of artifacts to be signed by cosign. The cosign step, has to be added to this workflow.

**Comment by mxmxchere** [comment]
The current state is almost working. Just having issues with AWS permissions for KMS signing.

**Comment by 5kt** [comment]
This needs to be kept in mind for certain improvements : https://github.com/gardenlinux/python-gardenlinux-lib/issues/75
Other than that, lgtm.

**Review by 5kt — APPROVED** [review]

**Comment by mxmxchere** [comment]
> This needs to be kept in mind for certain improvements : [gardenlinux/python-gardenlinux-lib#75](https://github.com/gardenlinux/python-gardenlinux-lib/issues/75) Other than that, lgtm.

Yes, I can only agree.

**Pull request merged**
