### PR TITLE
split platform test images

### PR DESCRIPTION
**Pull request by yeoldegrove**
**What this PR does / why we need it**:
Building and running the platform test containers can be enhanced, see proposals and discussions in #2260.

This PR introduces ...

## rename `container` dir to `tests/images`

- 54951350c63320ddd4f7659a0481a6c7bd0645d9 is a preparation for splitting the images

## python libraries handling

- commit 0f1aef29c1f96a5433eb8c172673a8cf132f8b17
  - `tests/Pipfile` now has sections for every platform so that python libraries can be installed on a per platform basis.
    - https://github.com/gardenlinux/gardenlinux/pull/2339/files#diff-0cf865e4615476360543b1643b1fd5ef3c0ad9630d351f7c0fdaf6df86df8676R23
  - `python`, `python-venv` and `libpython-dev` are installed from the gardenlinux repos
    - https://github.com/gardenlinux/gardenlinux/pull/2339/files#diff-33fc986f6c95d0839593f21b78eb7323e97fd1144f6242e47d36dbed1e084d98R37
  - every python library is installed via `pipenv` and frozen in `tests/Pipfile{,.lock}`
    - see image split commit d74fc279c8b9aca55186c7186dfe5ad1c58fc758

## dogfooding gardenlinux latest and reusing images to safe build time

- 9bbcb8eea7e7849e4f0c59df2d61ff58bf37083f
  - https://github.com/gardenlinux/gardenlinux/pull/2339/files#diff-33fc986f6c95d0839593f21b78eb7323e97fd1144f6242e47d36dbed1e084d98R5

  - The latest gardenlinux release from https://github.com/gardenlinux/gardenlinux/releases is used as base for platform test images.
    - see "get latest gardelinux version from container image"
- `ghcr.io/gardenlinux/gardenlinux` hosts now these images with a `latest` and `$gl_version` tag.
  - `platform-test-base`
  - `platform-test-ali`
  - `platform-test-aws`
  - `platform-test-azure`
  - `platform-test-firecracker` 
  - `platform-test-gcp`
  - `platform-test-kvm`
  - `platform-test-openstack`
- These images can be referenced and pulled in other CI workflows, e.g. `nightly`, without rebuilding them every time

### changes to workflows

- rename `build_container.yml` to `platform-test-images.yml`
- Adapted to new images.
  - e.g. https://github.com/gardenlinux/gardenlinux/pull/2339/files#diff-ee039e57848826f4f737a233148cbca40d8e869f7317f9de967d74a97b4eae22R8
- If changes are done to the platform-test-images, they are automatically rebuild.
  - After merging to `main`, they are automatically released with the `latest` and `$gl_version` tag to `ghcr.io`.
    - https://github.com/gardenlinux/gardenlinux/pull/2339/files
  - A manual `force_build` and `force_release` is possible in `.github/workflows/platform-test-images.yml`
    - https://github.com/gardenlinux/gardenlinux/pull/2339/files#diff-46f036fbb8dffcf8f76706d20210c05b601e5ad1e56d992b1a78d9840e9fe350R121

### time saved by this

- The current platform test image build in the `main`'s nightly is **~9-20m** long
  - https://github.com/gardenlinux/gardenlinux/actions/runs/10878343931/job/30181082293 
- The platform test image build from this PR runs in **~4m** if no tagged images exist
  - https://github.com/gardenlinux/gardenlinux/actions/runs/11213037576
- The platform test image build from this PR runs in **~30s** if tagged images exist 
  - https://github.com/gardenlinux/gardenlinux/actions/runs/11213940071

The pure build time is a bit shorter but the important part is that it can be skipped if a tagged image exists. Only the time to pull the images (~30s) is relevant in this case. 

### packages that were added to gardenlinux

- https://github.com/gardenlinux/repo/pull/23
  - apt-transport-https (to add https repos)
  - guestfish (vm image manipulation)
  - inetutils-ping
  - shellcheck (in case we want to run shellcheck tests in platform-test container)
  - unzip

## split of platform test images

- 9bbcb8eea7e7849e4f0c59df2d61ff58bf37083f

Platform test images are split based on the platform which makes it more transparent which components are needed and how much storage place they need. In certain scenarios, e.g. a developer that is only building an image for a certain platform,  the build time can be reduced in this way.

- `tests/images/platform-test{,-base}` now distinguishes `Containerfiles` for every platform and consume the `Pipfile` sections.
- `tests/images/Makefile` is an easy interface to build the images
  - The same make targets can be used in github actions and on a developer's machine.
- Platform test images are renamed and (overall) reduced in size. See table for details.

### images from current `main` branch (before changes)

| Name                          | Version  | Size   |
|-------------------------------|-------|--------|
| gardenlinux/base-test          | today | 2.02 GB|
| gardenlinux/platform-test      | today | 5.46 GB|

### images from current `platform-test-images` branch

| Name                                              | Version | Size    |
|---------------------------------------------------|---------|---------|
| gardenlinux/platform-test-base        | 1592.1  | 920 MB  |
| gardenlinux/platform-test-azure         | 1592.1  | 2.09 GB |
| gardenlinux/platform-test-gcp           | 1592.1  | 1.75 GB |
| gardenlinux/platform-test-kvm           | 1592.1  | 1.64 GB |
| gardenlinux/platform-test-openstack     | 1592.1  | 963 MB  |
| gardenlinux/platform-test-ali           | 1592.1  | 970 MB  |
| gardenlinux/platform-test-aws           | 1592.1  | 1.14 GB |
| gardenlinux/platform-test-firecracker   | 1592.1  | 927 MB  |

## Makefile as interface for platform test images

- 9bbcb8eea7e7849e4f0c59df2d61ff58bf37083f

```
❯ make --directory=tests/images
Usage: make [target]

general targets:
help					List available tasks of the project 
all					Build all platform test images   
all-push				Build and push all platform test images 
pull-platform-test-base			Pull the platform test base image 
pull-platform-test			Pull all platform test images 
build-platform-test-base		Build the platform test base image 
build-platform-test			Build all platform test images 
push-platform-test-base			Push the platform test base image 
push-release-platform-test-base		Push the platform test base image with release tag 
push-platform-test			Push all platform test images 
push-release-platform-test		Push all platform test images with release tag 

platform-specific targets:
pull-platform-test-ali                  Pull the platform test image for ali
pull-platform-test-aws                  Pull the platform test image for aws
pull-platform-test-azure                Pull the platform test image for azure
pull-platform-test-firecracker          Pull the platform test image for firecracker
pull-platform-test-gcp                  Pull the platform test image for gcp
pull-platform-test-kvm                  Pull the platform test image for kvm
pull-platform-test-openstack            Pull the platform test image for openstack
build-platform-test-ali                 Build the platform test image for ali
build-platform-test-aws                 Build the platform test image for aws
build-platform-test-azure               Build the platform test image for azure
build-platform-test-firecracker         Build the platform test image for firecracker
build-platform-test-gcp                 Build the platform test image for gcp
build-platform-test-kvm                 Build the platform test image for kvm
build-platform-test-openstack           Build the platform test image for openstack
push-platform-test-ali                  Push the platform test image for ali
push-platform-test-aws                  Push the platform test image for aws
push-platform-test-azure                Push the platform test image for azure
push-platform-test-firecracker          Push the platform test image for firecracker
push-platform-test-gcp                  Push the platform test image for gcp
push-platform-test-kvm                  Push the platform test image for kvm
push-platform-test-openstack            Push the platform test image for openstack
push-release-platform-test-ali          Push the platform test image for ali with release tag
push-release-platform-test-aws          Push the platform test image for aws with release tag
push-release-platform-test-azure        Push the platform test image for azure with release tag
push-release-platform-test-firecracker  Push the platform test image for firecracker with release tag
push-release-platform-test-gcp          Push the platform test image for gcp with release tag
push-release-platform-test-kvm          Push the platform test image for kvm with release tag
push-release-platform-test-openstack    Push the platform test image for openstack with release tag
```

## get latest gardelinux version from container image

I opened a new issue to discuss this topic https://github.com/gardenlinux/gardenlinux/issues/2389.
As of now there is some placeholder code that get's the latest version https://github.com/gardenlinux/gardenlinux/pull/2339/files#diff-7a3e648288401c0251740b9ca63b429c02d207fc2818fa158b5c590a56652351.

```
❯ bin/garden-version-resolver --help
usage: garden-version-resolver [-h] (--latest | --release RELEASE) [--commit] [--commit-short]

Fetch Garden Linux image version and corresponding Git commit using the GitHub CLI.

options:
  -h, --help         show this help message and exit
  --latest           Use the latest released Garden Linux
  --release RELEASE  Specify a Garden Linux release (e.g., 1592.1 or 1433)
  --commit           Fetch the full Git commit associated with the tag
  --commit-short     Fetch the short Git commit (first 8 characters) associated with the tag

❯ bin/garden-version-resolver --release 1592.1 --commit-short
1592.1-ec945aa9

❯ bin/garden-version-resolver --release 1443 --commit-short
1443.10-8d098305

❯ bin/garden-version-resolver --latest --commit-short
1592.1-ec945aa9
```

## update documentation

- d7b1db87fbff0e5908d302517b7eb233efa78654
  - include new `make` call and a bit of context in `tests/README.md`

**Which issue(s) this PR fixes**:
related to #2260

### CODE REVIEW

**Comment by fwilhe** [comment]
> bin/garden-gh-rel-latest-version queries github API to get latest release.

I see a potential issue here. Not sure how the 'latest' tag is set, but what if we create a new patch release for 1443 now, will this then be the 'latest' version, despite 1592.1 being newer really?

Maybe this could be another use-case for a maintained file with current release information as proposed [here](https://github.com/gardenlinux/gardenlinux/issues/2296)?

**Comment by yeoldegrove** [comment]
> > bin/garden-gh-rel-latest-version queries github API to get latest release.
> 
> I see a potential issue here. Not sure how the 'latest' tag is set, but what if we create a new patch release for 1443 now, will this then be the 'latest' version, despite 1592.1 being newer really?

Yes, this is very valid.

> 
> Maybe this could be another use-case for a maintained file with current release information as proposed [here](https://github.com/gardenlinux/gardenlinux/issues/2296)?

Another approach would be using the `latest` tag that was introduced here: https://github.com/gardenlinux/gardenlinux/pull/2338
But I would like to tag this somehow with the real gardenlinux release.

**Comment by yeoldegrove** [comment]
## get latest gardelinux version from container image

I opened a new issue to discuss this topic https://github.com/gardenlinux/gardenlinux/issues/2389.

**Comment by yeoldegrove** [comment]
Initial image build was triggered with `gh workflow run platform-test-images --ref platform-test-images -f force_build=true -f force_release=true -f gl_version=1646.0` and images are available here:
- https://github.com/gardenlinux/gardenlinux/pkgs/container/gardenlinux%2Fplatform-test-base
- https://github.com/gardenlinux/gardenlinux/pkgs/container/gardenlinux%2Fplatform-test-ali
- https://github.com/gardenlinux/gardenlinux/pkgs/container/gardenlinux%2Fplatform-test-aws
- https://github.com/gardenlinux/gardenlinux/pkgs/container/gardenlinux%2Fplatform-test-azure
- https://github.com/gardenlinux/gardenlinux/pkgs/container/gardenlinux%2Fplatform-test-gcp
- https://github.com/gardenlinux/gardenlinux/pkgs/container/gardenlinux%2Fplatform-test-kvm
- https://github.com/gardenlinux/gardenlinux/pkgs/container/gardenlinux%2Fplatform-test-openstack

**Comment by yeoldegrove** [comment]
Log file of a completed nightly build (without S3 upload):
https://github.com/gardenlinux/gardenlinux/actions/runs/11217059164

**Review by MrBatschner — APPROVED** [review]
/lgtm

**Pull request merged**
