### PR TITLE
bin/start-vm: add opensuse

### PR DESCRIPTION
**Pull request by kshtsk**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature user

```

### CODE REVIEW

**Comment by dnan0s** [comment]
We've been doing a quick Garden Linux Introduction and found out, the start-vm script does not work with suse, yet. This can be approved :)

**Comment by Akendo** [comment]
We had a broken nightly since there was a change on one of the upstream packages. This is why the pipeline is failing right now, we need to re-run this tomorrow. Once the tests are green, we can merge this. While I do not see any problem with this change, we recently had something similar.

**Comment by fwilhe** [comment]
`start-vm` has no influence on the failed tests.

**Comment by fwilhe** [comment]
Thanks for your contribution @kshtsk

**Review by fwilhe — APPROVED** [review]

**Pull request merged**
