### PR TITLE
feat: trustedboot

### PR DESCRIPTION
**Pull request by nkraetzschmar**
replace _secureboot and _readonly with _trustedboot

### CODE REVIEW

**Review by 5kt — APPROVED** [review]

**Comment by nkraetzschmar** [comment]
we should merge https://github.com/gardenlinux/builder/pull/97 first, as this is using it as its base

**Review by MrBatschner — APPROVED** [review]
/lgtm for the platform test part

**Comment by nkraetzschmar** [comment]
blocked by https://github.com/gardenlinux/builder/pull/97

(will still need to adjust the commitish in build script after merge in builder)

**Comment by nkraetzschmar** [comment]
replaced by #2341 to not have so many changes in one go

**Pull request closed without merging**
