### PR TITLE
update aws-action/configure-aws-credentials from v2 to v4

### LINKED ISSUE #1667: Bug: aws-actions/configure-aws-credentials@v2 fails
Sometimes the aws-actions/configure-aws-credentials@v2 fails in a nightly. 

```
Run aws-actions/configure-aws-credentials@v2
(node:1278) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Error: Error message: Cannot read properties of undefined (reading 'message')
```

### PR DESCRIPTION
**Pull request by chrinorse**
**How to categorize this PR?**

/kind bug
/area os
/os garden-linux

**What this PR does / why we need it**:
Update aws-action/configure-aws-credentials to its latest version `v4`, to solve problems with version `v2`.
**Which issue(s) this PR fixes**:
Fixes #1667 

**Special notes for your reviewer**:

**Release note**:

```feature user

```

### CODE REVIEW

**Comment by fwilhe** [comment]
Slightly related: Have we considered configuring dependabot for github actions to automate this?

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions

I'm not sure if that works with commit-ish version qualifiers which we recently introduced.. @Vincinator

**Review by Vincinator — APPROVED** [review]
lgtm

**Comment by Vincinator** [comment]
@fwilhe dependabot is a good idea.
Hm, we should enable depandabot for github actions that we do not pin via commit-hash.

For the commit-hash pinned we could also enable a dependabot alert that tells us that we need to check an update from the commit-hash pinned GH actions.

**Comment by fwilhe** [comment]
Dependabot is now configured

@Vincinator would we also use commit-ish for this action? I think it makes sense for the same reason as we did for the others.

**Comment by Vincinator** [comment]
Looks like this PR can be closes?

**Comment by fwilhe** [comment]
Hi @chrinorse 

I caused merge conflicts here, sorry for that.

I think when updating this to using commit-ish addressing for the aws action, the conflicts should be trivial to resolve. I'll not do anything here so we avoid duplicate effort, I closed the dependabot pr that was automatically created.

Thanks

**Pull request merged**
